name: Main

on:
  push:
    branches:
      - master
env:
  GO_VERSION: 1.18
jobs:
  unit-tests:
    name: 'Unit tests'
    strategy:
      fail-fast: false
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}
      - id: go-cache-paths
        run: |
          echo "::set-output name=go-mod::$(go env GOMODCACHE)"
      # Cache go mod cache to speedup deps downloads
      - name: Go Mod Cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.go-cache-paths.outputs.go-mod }}
          key: ${{ runner.os }}-go-mod-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.os }}-go-mod-
      - name: 'Run unit tests and generage HTML coverage report'
        run: |
          make unit-test
      - name: Update codecov report
        uses: codecov/codecov-action@v3
        with:
          files: ./build/coverage/ut_cov.out
          fail_ci_if_error: false
          verbose: true